### ISSUE TITLE
Inaccurate open source social movement history

### ISSUE THREAD

**Issue by MCTaylor17** [cambiecollective/open-source-start#1]
# Problem: 

The timeline shows social movement starts in 2010, but I believe the movement has been growing for a long time.  

# Steps to Reproduce:
@see: https://github.com/cambiecollective/open-source-start/blame/gh-pages/slides.md#L29

# Proposed Solution:
Consider mentioning some of the early moments in the open source movement

**Comment by keywordnew** [comment]
@MCTaylor17 fair point, it *did* start earlier. But which date would be worth mentioning in this short timeline?

**Comment by daffl** [comment]
I agree, I think it should be around the same time as GNU

**Comment by keywordnew** [comment]
@daffl Thanks David! I wasn't exactly sure, the early history of open source is something that I think I'd really like to read up on 💯

**Comment by MCTaylor17** [comment]
# Thank Youuuuuuuuuuuuuuuuuu!!!
